# Generated by Django 3.2.4 on 2021-06-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(db_index=True, max_length=100)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('productCategory', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=50)),
                ('productImage', models.CharField(max_length=60, null=True)),
                ('productStock', models.BooleanField(default=True)),
                ('productPrice', models.FloatField()),
                ('salePrice', models.FloatField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
